name: "Build Docker Image And Push To GitHub Container Registry"
description: "构建Docker镜像并推送至GitHub容器仓库"
inputs:
  username:
    description: "Docker username"
    required: true
  password:
    description: "Docker password"
    required: true
  dockerfile:
    description: "Dockerfile path"
    required: false
  tags:
    description: "Docker image tags"
    required: true
  args:
    description: "List of build-time variables"
  registry:
    description: "Docker registry"
    required: false
    default: "ghcr.io"
runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ inputs.tags }}
        file: ${{ inputs.dockerfile }}
        build-args: ${{ inputs.args }}
